# Generated by Django 5.0.14 on 2026-07-07 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/%Y/%m/', verbose_name='facture'),
        ),
    ]
