# Generated by Django 5.0.14 on 2026-07-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_invoice_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mobile_money_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='mobile_money_transaction_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Carte bancaire'), ('mobile_money', 'Mobile Money')], default='card', max_length=20, verbose_name='mode de paiement'),
        ),
    ]
