# Generated by Django 5.0.14 on 2026-07-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_mobile_money_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fedapay_payment_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='fedapay_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='fedapay_transaction_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Carte bancaire'), ('mobile_money', 'Mobile Money'), ('fedapay', 'FedaPay')], default='card', max_length=20, verbose_name='mode de paiement'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de paiement'), ('paid', 'Payée'), ('shipped', 'Expédiée'), ('delivered', 'Livrée'), ('cancelled', 'Annulée'), ('refunded', 'Remboursée'), ('b473ab0517064455a2d27a17a93c4b4b', 'Fedapay Transaction Id')], default='pending', max_length=50, verbose_name='statut'),
        ),
    ]
